apiVersion: v1
kind: Pod
metadata:
  labels:
    run: snat-check
  name: snat-check
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - ip-192-168-113-37.us-east-2.compute.internal
  hostNetwork: true
  containers:
  - image:  alpine:latest
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add: ["NET_ADMIN"]
    name: snat-check
    resources: {}
    command: ["sh"]
    args: ["-c","sleep 1000000"]
