apiVersion: v1
kind: Pod
metadata:
  labels:
    run: snat-client
  name: snat-client2
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
                    #- ip-192-168-113-37.us-east-2.compute.internal
            - ip-192-168-180-170.us-east-2.compute.internal
  hostNetwork: true
  containers:
  - args:
    - client
    - "--remote-addr"
    - 172.16.47.208:8080
    image: ghcr.io/gvych/snat-race-conn-test:latest
    imagePullPolicy: Always
    name: snat-server
