on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build and push
        uses: docker/build-push-action@v1
        with:
          #username: ${{ secrets.PACKAGES_USER }}
          #password: ${{ secrets.PACKAGES_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true

